---
title: "Kick or Receive"
format: html
---

### League-Wide Kickoff Analysis (2015-present)

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```

```{r load-packages}
library(nflfastR)
library(dplyr)
library(ggplot2)
```

```{r load-data}
plays <- load_pbp(2015:nflreadr::most_recent_season())
```

```{r create-opening_kickoffs}
opening_kickoffs <- plays |>
  dplyr::filter(play_type == "kickoff") |>
  dplyr::arrange(game_id, play_id) |>
  dplyr::group_by(game_id) |>
  dplyr::slice(1) |>
  dplyr::ungroup()
```

```{r determine_winner}
opening_kickoffs <- opening_kickoffs |>
  dplyr::mutate(
    winner = dplyr::case_when(
      result > 0 ~ home_team,
      result < 0 ~ away_team,
      TRUE ~ "tie"
    ),
    receiving_win = posteam == winner,
    receiving_home = posteam == home_team
  )
```

```{r chart_home_away}
opening_kickoffs |>
  dplyr::filter(winner != "tie") |>
  dplyr::mutate(
    Team_Type = dplyr::if_else(receiving_home, "Home", "Away"),
    initial_possession = "Received"
  ) |>
  dplyr::bind_rows(
    opening_kickoffs |>
      dplyr::filter(winner != "tie") |>
      dplyr::mutate(
        Team_Type = dplyr::if_else(receiving_home, "Away", "Home"),
        initial_possession = "Kicked",
        receiving_win = !receiving_win
      )
  ) |>
  dplyr::group_by(Team_Type, initial_possession) |>
  dplyr::summarise(
    win_pct = mean(receiving_win),
    .groups = "drop"
  ) |>
  ggplot(aes(x = initial_possession, y = win_pct, fill = Team_Type)) +
  geom_col(position = "dodge") +
  labs(
    x = "Initial Possession",
    y = "Win Percentage",
    fill = "Team"
  )
```







### By Team
```{r chart_per_team, fig.width=14, fig.height=20}
opening_kickoffs |>
  dplyr::filter(winner != "tie") |>
  dplyr::mutate(
    Team = posteam,
    Team_Type = dplyr::if_else(posteam == home_team, "Home", "Away"),
    initial_possession = "Received",
    team_win = posteam == winner
  ) |>
  dplyr::bind_rows(
    opening_kickoffs |>
      dplyr::filter(winner != "tie") |>
      dplyr::mutate(
        Team = defteam,
        Team_Type = dplyr::if_else(defteam == home_team, "Home", "Away"),
        initial_possession = "Kicked",
        team_win = defteam == winner
      )
  ) |>
  dplyr::group_by(Team, Team_Type, initial_possession) |>
  dplyr::summarise(
    win_pct = mean(team_win),
    .groups = "drop"
  ) |>
  ggplot(
    aes(
      x = reorder(Team, win_pct),
      y = win_pct,
      fill = initial_possession
    )
  ) +
  geom_col(position = "dodge") +
  coord_flip() +
  facet_wrap(~ Team_Type) +
  labs(
    x = "Team",
    y = "Win Percentage",
    fill = "Initial Possession"
  )
```



### By Coach
```{r chart_per_coach, fig.width=14, fig.height=70}
opening_kickoffs |>
  dplyr::filter(winner != "tie") |>
  dplyr::mutate(
    Coach = dplyr::if_else(posteam == home_team, home_coach, away_coach),
    Team_Type = dplyr::if_else(posteam == home_team, "Home", "Away"),
    initial_possession = "Received",
    team_win = posteam == winner
  ) |>
  dplyr::bind_rows(
    opening_kickoffs |>
      dplyr::filter(winner != "tie") |>
      dplyr::mutate(
        Coach = dplyr::if_else(defteam == home_team, home_coach, away_coach),
        Team_Type = dplyr::if_else(defteam == home_team, "Home", "Away"),
        initial_possession = "Kicked",
        team_win = defteam == winner
      )
  ) |>
  dplyr::group_by(Coach, Team_Type, initial_possession) |>
  dplyr::summarise(
    win_pct = mean(team_win),
    .groups = "drop"
  ) |>
  ggplot(aes(x = initial_possession, y = win_pct)) +
  geom_col() +
  facet_wrap(~ Coach + Team_Type, ncol=6) +
  labs(
    x = "Initial Possession",
    y = "Win Percentage"
  )
```
